version: '3.1'

services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: senior_challenge_api
    expose:
      - '5432'
volumes:
  db: